# Phase 1: PyTorch Foundations — Tensors & Operations

## What you'll learn
- What tensors are and why they matter
- Creating tensors in different ways
- Tensor data types and shapes
- Indexing, slicing, reshaping
- Math operations and broadcasting
- NumPy interop
- CPU ↔ GPU movement

---

## 1.1 Setup & GPU Check

First, let's import PyTorch and verify our environment. If `cuda` is available, we can use GPU acceleration.

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.10.0+cpu
CUDA available: False


## 1.2 What is a Tensor?

A **tensor** is a multi-dimensional array — the fundamental data structure in PyTorch.

| Dimensions | Name       | Example              |
|-----------|------------|----------------------|
| 0         | Scalar     | `torch.tensor(5)`    |
| 1         | Vector     | `torch.tensor([1,2,3])` |
| 2         | Matrix     | `torch.rand(3,3)`    |
| 3+        | nD Tensor  | `torch.rand(2,3,4)`  |

Think of tensors as **NumPy arrays that can run on GPUs** and **track gradients** for deep learning.

## 1.3 Creating Tensors

There are many ways to create tensors. Let's explore the most common ones.

In [ ]:
# From Python lists
a = torch.tensor([1, 2, 3])
print(f"From list: {a}")


# 2D tensor (matrix)
b = torch.tensor([[1, 2], [3, 4]])
print(f"Matrix:\n{b}")

# Zeros and ones
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
print(f"Zeros:\n{c}")
print(f"Ones:\n{d}")

# Random tensors (very common for weight initialization)
e = torch.rand(3, 3)     # uniform [0, 1)
f = torch.randn(3, 3)    # normal distribution (mean=0, std=1)
print(f"Random uniform:\n{e}")
print(f"Random normal:\n{f}")

# Range and linspace
g = torch.arange(0, 10, 2)        # [0, 2, 4, 6, 8]
h = torch.linspace(0, 1, steps=5) # [0.0, 0.25, 0.5, 0.75, 1.0]
print(f"Arange: {g}")
print(f"Linspace: {h}")

# Identity matrix
i = torch.eye(3)
print(f"Identity:\n{i}")

# Like another tensor (same shape/dtype)
j = torch.zeros_like(e)
print(f"Zeros like e:\n{j}")

From list: tensor([1, 2, 3])
Matrix:
tensor([[1, 2],
        [3, 4]])
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random uniform:
tensor([[0.0663, 0.5174, 0.7816],
        [0.8162, 0.6683, 0.6976],
        [0.4331, 0.4126, 0.6557]])
Random normal:
tensor([[-1.3996, -1.2935,  0.5871],
        [ 0.3512,  0.5548, -1.0114],
        [-1.3978,  0.5414, -0.5647]])
Arange: tensor([0, 2, 4, 6, 8])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
Identity:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Zeros like e:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## 1.4 Tensor Attributes: dtype, shape, device

Every tensor has 3 key attributes:
- **dtype** — data type (float32, int64, etc.)
- **shape** — dimensions
- **device** — where it lives (CPU or GPU)

In [3]:
x = torch.rand(3, 4)
print(f"Shape: {x.shape}")       # torch.Size([3, 4])
print(f"Dtype: {x.dtype}")       # torch.float32 (default)
print(f"Device: {x.device}")     # cpu
print(f"Ndim: {x.ndim}")         # 2
print(f"Numel: {x.numel()}")     # 12 (total elements)

# Specifying dtype at creation
y = torch.tensor([1, 2, 3], dtype=torch.float32)
z = torch.zeros(2, 2, dtype=torch.int64)
print(f"\ny dtype: {y.dtype}")
print(f"z dtype: {z.dtype}")

# Casting dtypes
w = y.to(torch.int32)
print(f"Casted: {w.dtype}")

Shape: torch.Size([3, 4])
Dtype: torch.float32
Device: cpu
Ndim: 2
Numel: 12

y dtype: torch.float32
z dtype: torch.int64
Casted: torch.int32


## 1.5 Indexing & Slicing

Works just like NumPy — same syntax, same intuition.

In [ ]:
x = torch.arange(12).reshape(3, 4)
print(f"x:\n{x}")

# Basic indexing
print(f"\nRow 0: {x[0]}")
print(f"Element [1,2]: {x[1, 2]}")
print(f"Last row: {x[-1]}")

# Slicing
print(f"\nFirst 2 rows:\n{x[:2]}")
print(f"Column 1: {x[:, 1]}")
print(f"Submatrix:\n{x[0:2, 1:3]}")

# Boolean indexing
mask = x > 5
print(f"\nMask (x > 5):\n{mask}")
print(f"Filtered: {x[mask]}")

# Fancy indexing
indices = torch.tensor([0, 2])
print(f"\nRows 0 and 2:\n{x[indices]}")

x:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Row 0: tensor([0, 1, 2, 3])
Element [1,2]: 6
Last row: tensor([ 8,  9, 10, 11])

First 2 rows:
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
Column 1: tensor([1, 5, 9])
Submatrix:
tensor([[1, 2],
        [5, 6]])

Mask (x > 5):
tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
Filtered: tensor([ 6,  7,  8,  9, 10, 11])

Rows 0 and 2:
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])


## 1.6 Reshaping Tensors

Reshaping is critical in deep learning — you'll constantly reshape data between layers.

Key functions:
- `view()` — reshape (must be contiguous in memory)
- `reshape()` — reshape (works even if not contiguous, may copy)
- `permute()` — reorder dimensions
- `squeeze()` / `unsqueeze()` — remove/add dimensions of size 1
- `flatten()` — collapse to 1D

In [ ]:
x = torch.arange(12)
print(x)
print(f"Original: {x.shape}")

# view / reshape
a = x.view(3, 4)
b = x.reshape(2, 6)
print(f"view(3,4):\n{a}")
print(f"reshape(2,6):\n{b}")

# -1 infers the dimension
c = x.view(3, -1)  # 3 rows, auto-compute columns → (3, 4)
print(f"view(3,-1): {c.shape}")

# squeeze / unsqueeze
d = torch.rand(1, 3, 1)
print(f"\nBefore squeeze: {d.shape}")    # (1, 3, 1)
print(f"After squeeze: {d.squeeze().shape}")  # (3,)

e = torch.rand(3)
print(f"Before unsqueeze: {e.shape}")    # (3,)
print(f"unsqueeze(0): {e.unsqueeze(0).shape}")  # (1, 3)
print(f"unsqueeze(1): {e.unsqueeze(1).shape}")  # (3, 1)

# permute — reorder axes
img = torch.rand(3, 224, 224)  # C, H, W
img_hwc = img.permute(1, 2, 0) # H, W, C
print(f"\nCHW: {img.shape} → HWC: {img_hwc.shape}")

# flatten
f = torch.rand(2, 3, 4)
print(f"Flatten: {f.flatten().shape}")           # (24,)
print(f"Flatten(1): {f.flatten(start_dim=1).shape}")  # (2, 12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original: torch.Size([12])
view(3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
reshape(2,6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
view(3,-1): torch.Size([3, 4])

Before squeeze: torch.Size([1, 3, 1])
After squeeze: torch.Size([3])
Before unsqueeze: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])

CHW: torch.Size([3, 224, 224]) → HWC: torch.Size([224, 224, 3])
Flatten: torch.Size([3])
Flatten(1): torch.Size([1, 3])


## 1.7 Tensor Math Operations

PyTorch supports all standard math operations — element-wise, reduction, and matrix ops.

In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Element-wise operations
print("--- Element-wise ---")
print(f"Add: {a + b}")
print(f"Mul: {a * b}")
print(f"Div: {a / b}")
print(f"Power: {a ** 2}")

# Reduction operations
print("\n--- Reductions ---")
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(f"Sum: {x.sum()}")
print(f"Sum axis=0: {x.sum(dim=0)}")   # column-wise
print(f"Sum axis=1: {x.sum(dim=1)}")   # row-wise
print(f"Mean: {x.mean()}")
print(f"Max: {x.max()}")
print(f"Argmax: {x.argmax()}")

# Matrix multiplication
print("\n--- Matrix Multiply ---")
m1 = torch.rand(2, 3)
m2 = torch.rand(3, 4)
result = m1 @ m2              # same as torch.matmul(m1, m2)
print(f"(2,3) @ (3,4) = {result.shape}")

# Dot product
print(f"\nDot product: {torch.dot(a, b)}")

# Batch matrix multiply
batch1 = torch.rand(8, 3, 4)
batch2 = torch.rand(8, 4, 5)
result = torch.bmm(batch1, batch2)
print(f"Batch matmul: {result.shape}")  # (8, 3, 5)

--- Element-wise ---
Add: tensor([5., 7., 9.])
Mul: tensor([ 4., 10., 18.])
Div: tensor([0.2500, 0.4000, 0.5000])
Power: tensor([1., 4., 9.])

--- Reductions ---
Sum: 10.0
Sum axis=0: tensor([4., 6.])
Sum axis=1: tensor([3., 7.])
Mean: 2.5
Max: 4.0
Argmax: 3

--- Matrix Multiply ---
(2,3) @ (3,4) = torch.Size([2, 4])

Dot product: 32.0
Batch matmul: torch.Size([8, 3, 5])


## 1.8 Broadcasting

Broadcasting lets you do operations on tensors with **different shapes** without copying data.

**Rules:**
1. Dimensions are compared from the **right**
2. Dimensions must be **equal**, or one of them must be **1**
3. Missing dimensions are treated as **1**

In [136]:
# Scalar broadcast
x = torch.tensor([1.0, 2.0, 3.0])
print(f"x + 10 = {x + 10}")

# (3,4) + (4,) → broadcasts row across all rows
a = torch.ones(3, 4)
print(f"a: {a}")
b = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"\n(3,4) + (4,):\n{a + b}")

# (3,1) + (1,4) → broadcasts both to (3,4)
c = torch.tensor([[1], [2], [3]])  # (3,1)
d = torch.tensor([[10, 20, 30, 40]])  # (1,4)
print(f"\n(3,1) + (1,4):\n{c + d}")

# Common use: normalize each feature column
data = torch.rand(5, 3)  # 5 samples, 3 features
mean = data.mean(dim=0)  # shape (3,)
std = data.std(dim=0)    # shape (3,)
normalized = (data - mean) / std
print(f"\nNormalized mean: {normalized.mean(dim=0)}")

x + 10 = tensor([11., 12., 13.])
a: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

(3,4) + (4,):
tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])

(3,1) + (1,4):
tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])

Normalized mean: tensor([7.1526e-08, 4.1723e-08, 4.7684e-08])


## 1.9 NumPy ↔ Tensor Conversion

PyTorch and NumPy share memory when on CPU — changes to one affect the other (unless you `.clone()`).

In [8]:
# NumPy → Tensor
np_arr = np.array([1.0, 2.0, 3.0])
tensor_from_np = torch.from_numpy(np_arr)
print(f"From NumPy: {tensor_from_np}")

# They share memory!
np_arr[0] = 99
print(f"After modifying numpy: {tensor_from_np}")  # also changed!

# Tensor → NumPy
t = torch.tensor([4.0, 5.0, 6.0])
np_from_tensor = t.numpy()
print(f"\nTo NumPy: {np_from_tensor}")

# Safe copy (no shared memory)
safe_tensor = torch.from_numpy(np_arr).clone()
np_arr[0] = 0
print(f"\nCloned tensor unaffected: {safe_tensor}")

From NumPy: tensor([1., 2., 3.], dtype=torch.float64)
After modifying numpy: tensor([99.,  2.,  3.], dtype=torch.float64)

To NumPy: [4. 5. 6.]

Cloned tensor unaffected: tensor([99.,  2.,  3.], dtype=torch.float64)


## 1.10 CPU ↔ GPU

Moving tensors to GPU enables massive parallelism. Always check availability first.

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Create on device directly
x = torch.rand(3, 3, device=device)
print(f"x device: {x.device}")

# Move existing tensor
y = torch.rand(3, 3)
y = y.to(device)
print(f"y device: {y.device}")

# Operations must be on same device
z = x + y  # works — both on same device
print(f"z device: {z.device}")

# Move back to CPU (needed for NumPy conversion)
z_cpu = z.cpu()
print(f"z_cpu device: {z_cpu.device}")
print(f"As numpy: {z_cpu.numpy()}")

Using device: cpu
x device: cpu
y device: cpu
z device: cpu
z_cpu device: cpu
As numpy: [[1.3458774  0.68897897 1.448477  ]
 [0.28806144 1.1020058  1.3536632 ]
 [0.77398044 1.5341122  0.67462677]]


## 1.11 In-place Operations

Operations ending with `_` modify the tensor in-place (saves memory but can break autograd).

In [138]:
x = torch.tensor([1.0, 2.0, 3.0])

# Regular (creates new tensor)
y = x.add(10)
print(f"x unchanged: {x}")
print(f"y = x + 10: {y}")

# In-place (modifies x)
x.add_(10)
print(f"x after add_: {x}")

# Other in-place ops
x.zero_()       # fill with zeros
print(f"After zero_: {x}")
x.fill_(7)      # fill with value
print(f"After fill_(7): {x}")

x unchanged: tensor([1., 2., 3.])
y = x + 10: tensor([11., 12., 13.])
x after add_: tensor([11., 12., 13.])
After zero_: tensor([0., 0., 0.])
After fill_(7): tensor([7., 7., 7.])


## ✅ Phase 1 Summary

You now know how to:
- Create tensors in multiple ways
- Inspect shape, dtype, device
- Index, slice, and reshape tensors
- Perform math ops and matrix multiplication
- Use broadcasting for efficient computation
- Convert between NumPy and PyTorch
- Move data between CPU and GPU

**Next → Phase 2: Autograd & Automatic Differentiation**